In [61]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler
from math import sqrt

# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input
from keras.utils import to_categorical

In [14]:
data = pd.read_csv('C:/Users/ADMIN/Desktop/Code/Jupyter N_book/Keras/train.csv')
y_train = data.label
x_train = data.drop('label',axis = 1)

In [62]:
num_classes = len(y_train.unique())
Y_val= y_train.unique()
X_val = np.arange(0,256)

y_train = to_categorical(y_train)

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [63]:
print(y_train.shape,'\t',x_train.shape)

(42000, 10) 	 (42000, 784)


## __Implementing neural network__

In [64]:
model = Sequential()

model.add(Input(shape = (784,)))

model.add(Dense(1000, activation='relu'))
model.add(Dense(500, activation='relu'))
model.add(Dense(250, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_26 (Dense)                     │ (None, 1000)                │         785,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_27 (Dense)                     │ (None, 500)                 │         500,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_28 (Dense)                     │ (None, 250)                 │         125,250 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_29 (Dense)                     │ (None, 100)                 │          25,100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_30 (Dense)                     │ (None, 50)                  │           5,050 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_31 (Dense)                     │ (None, 10)                  │             510 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,441,410 (5.50 MB)

 Trainable params: 1,441,410 (5.50 MB)

 Non-trainable params: 0 (0.00 B)

In [65]:
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

In [66]:
XX_train,XX_test,YY_train,YY_test = train_test_split(x_train,y_train,test_size=0.33)
YY_test.shape

(13860, 10)

In [68]:

model.fit(XX_train, YY_train, epochs=100)

Epoch 1/100
880/880 ━━━━━━━━━━━━━━━━━━━━ 27s 31ms/step - accuracy: 0.9446 - loss: 0.1883
Epoch 2/100
880/880 ━━━━━━━━━━━━━━━━━━━━ 40s 30ms/step - accuracy: 0.9554 - loss: 0.1558
Epoch 3/100
880/880 ━━━━━━━━━━━━━━━━━━━━ 39s 27ms/step - accuracy: 0.9601 - loss: 0.1383
Epoch 4/100
880/880 ━━━━━━━━━━━━━━━━━━━━ 41s 27ms/step - accuracy: 0.9719 - loss: 0.0931
Epoch 5/100
880/880 ━━━━━━━━━━━━━━━━━━━━ 24s 27ms/step - accuracy: 0.9672 - loss: 0.1126
Epoch 6/100
880/880 ━━━━━━━━━━━━━━━━━━━━ 25s 28ms/step - accuracy: 0.9702 - loss: 0.1097
Epoch 7/100
880/880 ━━━━━━━━━━━━━━━━━━━━ 25s 28ms/step - accuracy: 0.9745 - loss: 0.0941
Epoch 8/100
880/880 ━━━━━━━━━━━━━━━━━━━━ 25s 28ms/step - accuracy: 0.9818 - loss: 0.0658
Epoch 9/100
880/880 ━━━━━━━━━━━━━━━━━━━━ 25s 28ms/step - accuracy: 0.9788 - loss: 0.0786
Epoch 10/100
880/880 ━━━━━━━━━━━━━━━━━━━━ 25s 28ms/step - accuracy: 0.9818 - loss: 0.0735
Epoch 11/100
880/880 ━━━━━━━━━━━━━━━━━━━━ 25s 28ms/step - accuracy: 0.9843 - loss: 0.0585
Epoch 12/100
880/88

In [69]:
pred_train= model.predict(XX_train)
scores = model.evaluate(XX_train, YY_train, verbose=0)
print('Accuracy on training data: {}% \n Error on training data: {}'.format(scores[1], 1 - scores[1]))   
 
pred_test= model.predict(XX_test)
scores2 = model.evaluate(XX_test, YY_test, verbose=0)
print('Accuracy on test data: {}% \n Error on test data: {}'.format(scores2[1], 1 - scores2[1]))

880/880 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step
Accuracy on training data: 0.9696162343025208% 
 Error on training data: 0.030383765697479248
434/434 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step
Accuracy on test data: 0.9422078132629395% 
 Error on test data: 0.05779218673706055


### __Testing Actual Test__

In [70]:
real_test = pd.read_csv('C:/Users/ADMIN/Desktop/Code/Jupyter N_book/Keras/test.csv')
real_test.shape

(28000, 784)

In [74]:
real_pred = model.predict(real_test)
real_pred

875/875 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step


array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 2.3295394e-27],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [8.7107755e-06, 9.8861775e-34, 0.0000000e+00, ..., 8.9615460e-05,
        2.5326326e-05, 9.9232554e-01],
       ...,
       [0.0000000e+00, 0.0000000e+00, 4.1459295e-30, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [3.1674143e-09, 0.0000000e+00, 0.0000000e+00, ..., 3.6975248e-07,
        3.5080834e-08, 9.9970669e-01],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 4.6672582e-18]], dtype=float32)

In [100]:
real_values = np.argmax(real_pred,axis = 1, out = None)
real_values

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [96]:
S_riyal = pd.Series(real_values)
PD_riyal = pd.DataFrame({
    'Label': S_riyal
})
PD_riyal.shape

(28000, 1)

In [103]:
PD_riyal.index = np.arange(1,28001)
PD_riyal.index.name = "ImageID"

In [104]:
PD_riyal.to_csv('Digits_Pred_PranaySol.csv')